(()=>{
  if(globalThis.__ATS_TRADE_HANDOFF__)return;globalThis.__ATS_TRADE_HANDOFF__=true;
  const visible=el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>24&&r.height>18&&s.visibility!=='hidden'&&s.display!=='none'};
  const norm=v=>String(v||'').trim().toLowerCase();
  const tokens={BUY:['comprar','compra','buy','call','alta','up'],SELL:['vender','venda','sell','put','baixa','down']};
  const money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)):null;
  function score(el,direction){const t=norm(`${el.textContent||''} ${el.getAttribute('aria-label')||''} ${el.getAttribute('title')||''}`);let n=0;for(const x of tokens[direction]||[])if(t.includes(x))n+=x.length>4?4:2;if(el.matches('button,[role="button"],input[type="button"],input[type="submit"]'))n+=2;return n}
  function clear(){document.querySelectorAll('[data-ats-trade-target]').forEach(el=>{el.removeAttribute('data-ats-trade-target');el.style.removeProperty('outline');el.style.removeProperty('outline-offset');el.style.removeProperty('box-shadow');el.style.removeProperty('scroll-margin')});document.getElementById('ats-trade-handoff-toast')?.remove()}
  function toast(intent,target){const el=document.createElement('div');el.id='ats-trade-handoff-toast';const buy=intent.direction==='BUY',stake=money(intent.suggestedStake),scoreValue=Number.isFinite(Number(intent.aiScore))?Math.round(Number(intent.aiScore)):null;Object.assign(el.style,{position:'fixed',zIndex:'2147483647',top:'18px',left:'50%',transform:'translateX(-50%)',minWidth:'260px',maxWidth:'420px',padding:'13px 15px',borderRadius:'14px',background:'rgba(7,12,21,.97)',border:`1px solid ${buy?'rgba(79,224,165,.4)':'rgba(255,108,134,.38)'}`,boxShadow:'0 18px 48px rgba(0,0,0,.52)',color:'#fff',font:'600 12px system-ui',pointerEvents:'none'});const title=document.createElement('div');title.style.cssText=`font-weight:900;font-size:13px;color:${buy?'#79eabb':'#ff99aa'};margin-bottom:5px`;title.textContent=`ATS • ${buy?'COMPRA':'VENDA'} PREPARADA`;const meta=document.createElement('div');meta.style.cssText='color:#aeb9c9;font-size:11px;line-height:1.55';meta.textContent=[intent.asset,intent.timeframe,intent.expiration?`exp. ${intent.expiration}`:null,scoreValue!=null?`nota IA ${scoreValue}`:null,stake?`valor sugerido ${stake}`:null].filter(Boolean).join(' • ');const hint=document.createElement('div');hint.style.cssText='color:#77869d;font-size:10px;margin-top:5px';hint.textContent=target?'Botão localizado e destacado. Confirme manualmente na plataforma.':'Não localizei o botão com segurança. Confirme manualmente na plataforma.';el.append(title,meta,hint);document.documentElement.appendChild(el);setTimeout(()=>el.remove(),5200)}
  chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type!=='ATS_HIGHLIGHT_TRADE')return;clear();const direction=String(m.direction||'').toUpperCase(),all=[...document.querySelectorAll('button,[role="button"],input[type="button"],input[type="submit"],a')].filter(visible),ranked=all.map(el=>({el,s:score(el,direction)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s),target=ranked[0]?.el||null;if(target){target.setAttribute('data-ats-trade-target',direction);target.style.outline=direction==='BUY'?'3px solid #33e89b':'3px solid #ff6178';target.style.outlineOffset='4px';target.style.boxShadow=direction==='BUY'?'0 0 30px rgba(51,232,155,.58)':'0 0 30px rgba(255,97,120,.58)';target.style.scrollMargin='120px';target.scrollIntoView({behavior:'smooth',block:'center'})}toast(m,target);send({ok:true,found:!!target,label:target?String(target.textContent||target.getAttribute('aria-label')||'').trim().slice(0,80):null});return true});
})();
