import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
test('0.11.13 captures the visible canvas candle countdown and keeps derived clock from overwriting it', () => { const manifest=JSON.parse(read('manifest.json')); const probe=read('src/content/canvas-countdown-probe.js'); const clock=read('src/content/market-cycle-clock-v4.js'); assert.equal(manifest.version,'0.11.13'); assert.ok(manifest.content_scripts.some(row=>(row.js||[]).includes('src/content/canvas-countdown-probe.js'))); assert.match(probe,/ATS_CANVAS_CANDLE_COUNTDOWN/); assert.match(probe,/fillText.*strokeText/s); assert.match(clock,/canvas-visible-countdown/); assert.match(clock,/progressed/); assert.match(clock,/Date\.now\(\) - canvasVerifiedAt < 2300/); assert.match(clock,/clockSource: 'trader-dom-countdown'/); });
test('fresh visual selection wins over a stale protocol-selected asset during chart switches', () => { const focus=read('src/content/focused-asset-protocol.js'); assert.match(focus,/function freshVisual\(asset\)/); assert.match(focus,/String\(meta\.source \|\| ''\) === 'protocol-selected'/); assert.match(focus,/if \(freshVisual\(winner\.asset\)\) return/); assert.match(focus,/Network\/app state can lag briefly/); });
test('CasaTrade UI observer reads visible balance, stake, payout and expiration without inventing zeros', () => { const observer=read('src/content/casatrade-ui-observer-v2.js'); const background=read('src/background-platform-controls.js'); assert.match(observer,/balanceCandidate/); assert.match(observer,/depositar\|deposit\|saldo\|balance/); assert.match(observer,/labeledMoney\(\/\\bvalor/); assert.match(observer,/payoutCandidate/); assert.match(observer,/expirationCandidate/); assert.match(observer,/ATS_ACCOUNT_METRICS/); assert.match(observer,/ATS_PLATFORM_CONTROLS_OBSERVED/); assert.match(background,/expirationGuard/); assert.match(background,/CasaTrade em \$\{actual\}; esperado \$\{desired\}/); });
test('expiration is configurable and blocks handoff when CasaTrade is not aligned', () => { const html=read('src/sidepanel/index.html'); const guard=read('src/sidepanel/expiration-guard-ui.js'); const handoff=read('src/sidepanel/trade-handoff-ui.js'); assert.match(html,/id="desiredExpiration"/); assert.match(html,/value="60s" selected/); assert.match(guard,/DEFAULT_EXPIRATION = '60s'/); assert.match(guard,/ENTRADA BLOQUEADA/); assert.match(handoff,/actualExpiration !== desiredExpiration/); assert.match(handoff,/ENTRADA BLOQUEADA/); assert.doesNotMatch(handoff,/\.click\(\)/); });
test('overlay is clipped to chart and does not paint a generic syncing banner over CasaTrade', () => { const overlay=read('src/content/analysis-visual-overlay-v2.js'); assert.match(overlay,/function lowerChartBoundary\(rect\)/); assert.match(overlay,/portf\[oó\]lio total/); assert.match(overlay,/overflow: 'hidden'/); assert.match(overlay,/only actionable lines belong here/); assert.doesNotMatch(overlay,/SUPORTE \/ RESISTÊNCIA • SINCRONIZANDO VELA/); });
