const API='https://ats-control-center-v07-production.up.railway.app';
const SUPPORT='5535991429262';
const $=id=>document.getElementById(id);
let currentState={};

const manifest=chrome.runtime.getManifest();
$('version').textContent=`v${manifest.version} • ACESSO DO CLIENTE`;

function show(id){for(const x of ['loadingView','activationView','customerView'])$(x).hidden=x!==id}
function fmtDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('pt-BR')}
function activeLicense(l){return !!l&&l.status==='active'&&(!l.expiresAt||Date.parse(l.expiresAt)>Date.now())}
function usage(l={}){if(l.plan==='trial'||l.isTrial){if(l.totalLimit!=null)return`${Number(l.usedTotal)||0} / ${l.totalLimit} total`;return`${Number(l.usedToday)||0} usado(s)`}if(l.dailyLimit==null)return`${Number(l.usedToday)||0} hoje • ilimitado`;return`${Number(l.usedToday)||0} / ${l.dailyLimit} hoje`}
function errorText(e){return({license_required:'Cole uma chave válida para ativar.',license_not_found:'Chave não encontrada. Confira e tente novamente.',license_inactive:'Esta licença está inativa. Renove ou fale com o suporte.',license_expired:'Esta licença venceu. Renove o acesso.',device_locked:'Esta licença já está vinculada a outro aparelho.',device_limit_reached:'Esta licença já atingiu o limite de aparelhos.',trial_limit_reached:'Seu Trial já utilizou todos os sinais disponíveis.',daily_limit_reached:'O limite diário deste plano foi atingido.',backend_unreachable:'Não foi possível falar com o servidor ATS.',connect_code_invalid:'Código inválido, usado ou expirado.',trial_device_already_used:'Este aparelho já utilizou um Trial em outra conta.',permission_denied:'Permissão de acesso ao servidor ATS não foi concedida.'})[e]||'Não foi possível concluir. Tente novamente.'}
async function ensureInstallId(){const x=await chrome.storage.local.get('atsInstallationId');if(x.atsInstallationId)return x.atsInstallationId;const id=crypto.randomUUID();await chrome.storage.local.set({atsInstallationId:id});return id}
async function ensureApiPermission(){try{const origin=`${new URL(API).origin}/*`;if(await chrome.permissions.contains({origins:[origin]}))return true;return await chrome.permissions.request({origins:[origin]})}catch{return false}}
async function storeSession(d,key=''){const set={};if(key||d.licenseKey)set.atsLicenseKey=String(key||d.licenseKey||'');if(d.clientToken)set.atsClientToken=String(d.clientToken);if(d.clientTokenExpiresAt)set.atsClientTokenExpiresAt=Number(d.clientTokenExpiresAt)||0;if(d.accountToken)set.atsAccountToken=String(d.accountToken);if(d.accountTokenExpiresAt)set.atsAccountTokenExpiresAt=Number(d.accountTokenExpiresAt)||0;const old=(await chrome.storage.local.get('scannerState')).scannerState||{};if(d.license)set.scannerState={...old,license:{...(old.license||{}),...d.license,error:null}};await chrome.storage.local.set(set)}
async function directLicense(path,key){if(!(await ensureApiPermission()))return{ok:false,error:'permission_denied'};try{const r=await fetch(`${API}${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({licenseKey:String(key||'').trim().toUpperCase(),installationId:await ensureInstallId(),version:manifest.version})});const d=await r.json().catch(()=>({}));if(r.ok&&d.ok)await storeSession(d,key);return{ok:r.ok&&!!d.ok,status:r.status,...d}}catch{return{ok:false,error:'backend_unreachable'}}}
async function runtime(type,payload={}){try{return await chrome.runtime.sendMessage({type,...payload})}catch{return null}}
async function activateKey(key){const normalized=String(key||'').trim().toUpperCase();if(!normalized)return{ok:false,error:'license_required'};let r=await runtime('ATS_ACTIVATE_LICENSE',{key:normalized});if(!r||(!r.ok&&r.error==='backend_unreachable'))r=await directLicense('/v1/license/activate',normalized);return r||{ok:false,error:'backend_unreachable'}}
async function validateAccess(){let r=await runtime('ATS_VALIDATE_LICENSE');if(r?.ok)return r;const x=await chrome.storage.local.get('atsLicenseKey'),key=String(x.atsLicenseKey||'').trim();if(!key)return r||{ok:false,error:'license_required'};const fallback=await directLicense('/v1/license/validate',key);return fallback?.ok?fallback:(r||fallback)}
async function getState(){const s=await runtime('ATS_GET_STATE');if(s)return s;const x=await chrome.storage.local.get('scannerState');return x.scannerState||{}}
function renderCustomer(state={}){currentState=state;const l=state.license||{};show('customerView');$('statusDot').classList.add('on');$('planName').textContent=(l.planLabel||l.plan||'ATIVO').toUpperCase();$('planBadge').textContent='ATIVO';$('planTitle').textContent=l.plan==='lifetime'?'Plano Vitalício ativo':'Acesso ativo';$('planText').textContent=l.plan==='lifetime'?'Seu acesso vitalício está vinculado a este aparelho.':'Sua licença está ativa e vinculada a este aparelho.';$('expiry').textContent=l.plan==='lifetime'?'VITALÍCIO':l.expiresAt?fmtDate(l.expiresAt):'SEM DATA';$('usage').textContent=usage(l);$('device').textContent=l.deviceLocked||Number(l.devices)>0?'VINCULADO':'LIVRE';$('customerStatus').className='notice ok';$('customerStatus').textContent='Acesso validado. Abra o scanner completo para configurar a operação antes de iniciar.'}
function renderActivation(state={},message=''){currentState=state;const l=state.license||{};show('activationView');$('statusDot').classList.remove('on');$('activationText').textContent=l.status==='expired'?'Seu acesso venceu. Você pode renovar ou ativar uma nova chave neste aparelho.':l.status==='device_locked'?'Esta licença está vinculada a outro aparelho. Use outra chave ou peça liberação ao suporte.':'Cole sua chave de licença para liberar o scanner neste aparelho.';if(message){$('activationStatus').className='notice bad';$('activationStatus').textContent=message}else{$('activationStatus').className='notice';$('activationStatus').textContent='Na primeira ativação, a licença fica vinculada a este aparelho.'}}
async function bootstrap(){show('loadingView');const r=await validateAccess().catch(()=>({ok:false,error:'backend_unreachable'}));const state=await getState();if(r?.ok&&activeLicense(r.license||state.license)){state.license=r.license||state.license;renderCustomer(state)}else renderActivation(state,r?.error&&r.error!=='license_required'?errorText(r.error):'')}
async function activate(){const btn=$('activateBtn'),key=$('licenseKey').value;btn.disabled=true;btn.textContent='ATIVANDO...';$('activationStatus').className='notice';$('activationStatus').textContent='Validando licença e vinculando este aparelho...';const r=await activateKey(key);btn.disabled=false;btn.textContent='ATIVAR LICENÇA';if(r?.ok){$('licenseKey').value='';const state=await getState();state.license=r.license||state.license;renderCustomer(state);return}$('activationStatus').className='notice bad';$('activationStatus').textContent=errorText(r?.error)}
async function connectAccount(){const btn=$('connectAccountBtn'),code=String($('accountCode').value||'').replace(/\D/g,'').slice(0,6);if(code.length!==6){$('activationStatus').className='notice bad';$('activationStatus').textContent='Digite os 6 números gerados no portal ATS.';return}btn.disabled=true;btn.textContent='CONECTANDO...';try{if(!(await ensureApiPermission()))throw Object.assign(new Error('permission_denied'),{code:'permission_denied'});const r=await fetch(`${API}/v1/customer/extension/exchange`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,installationId:await ensureInstallId(),version:manifest.version})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){$('activationStatus').className='notice bad';$('activationStatus').textContent=errorText(d.error||'connect_code_invalid');return}await storeSession(d);$('accountCode').value='';await runtime('ATS_VALIDATE_LICENSE');const state=await getState();state.license=d.license||state.license;renderCustomer(state)}catch(e){$('activationStatus').className='notice bad';$('activationStatus').textContent=errorText(e.code||'backend_unreachable')}finally{btn.disabled=false;btn.textContent='CONECTAR CONTA'}}
async function openScanner(){const btn=$('openScannerBtn');btn.disabled=true;try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(chrome.sidePanel?.open&&tab?.windowId!=null){try{await chrome.sidePanel.open({windowId:tab.windowId});window.close();return}catch{}}await chrome.tabs.create({url:chrome.runtime.getURL('src/sidepanel/index.html')});window.close()}finally{btn.disabled=false}}
async function openPortal(){await chrome.tabs.create({url:`${API}/`});window.close()}
async function focusCasaTrade(){const tabs=await chrome.tabs.query({});const t=tabs.find(x=>/https:\/\/[^/]*casatrade\.(com|io)\//i.test(x.url||''));if(t?.id){await chrome.tabs.update(t.id,{active:true});if(t.windowId!=null)await chrome.windows.update(t.windowId,{focused:true}).catch(()=>{})}else await chrome.tabs.create({url:'https://trade.casatrade.com/'})}
async function revalidate(){const b=$('validateBtn');b.disabled=true;$('customerStatus').textContent='Sincronizando acesso...';const r=await validateAccess();b.disabled=false;if(r?.ok){const state=await getState();state.license=r.license||state.license;renderCustomer(state)}else{$('customerStatus').className='notice bad';$('customerStatus').textContent=errorText(r?.error);setTimeout(()=>renderActivation(currentState,errorText(r?.error)),700)}}
function askRenewal(){const l=currentState.license||{};const msg=`Olá! Quero renovar meu acesso ao AI Trading Scanner. Plano atual: ${l.planLabel||l.plan||'não identificado'}.`;return`https://wa.me/${SUPPORT}?text=${encodeURIComponent(msg)}`}

$('activateBtn').addEventListener('click',activate);
$('licenseKey').addEventListener('keydown',e=>{if(e.key==='Enter')activate()});
$('accountCode').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,6)});
$('accountCode').addEventListener('keydown',e=>{if(e.key==='Enter')connectAccount()});
$('connectAccountBtn').addEventListener('click',connectAccount);
$('openPortalBtn').addEventListener('click',openPortal);
$('openScannerBtn').addEventListener('click',openScanner);
$('connectPlatformBtn').addEventListener('click',focusCasaTrade);
$('renewBtn').addEventListener('click',openPortal);
$('changeKeyBtn').addEventListener('click',()=>{renderActivation(currentState);$('licenseKey').focus()});
$('validateBtn').addEventListener('click',revalidate);
$('supportBtn').addEventListener('click',e=>{e.currentTarget.href=askRenewal()});

bootstrap();
