const API='https://ats-control-center-v07-production.up.railway.app';
const SUPPORT='5535991429262';
const ONBOARDING_KEY='atsPopupOnboardingV1';
const VALIDATED_AT='atsLicenseValidatedAt';
const LICENSE_SNAPSHOT='atsLicenseSnapshot';
const $=id=>document.getElementById(id);
let currentState={};
let tutorialIndex=0;

const manifest=chrome.runtime.getManifest();
$('version').textContent=`v${manifest.version} • ACESSO DO CLIENTE`;

const tutorialSteps=[
  {icon:'1',title:'Abra a CasaTrade',text:'Entre na sua conta Demo ou real e deixe a traderoom carregada antes de iniciar o scanner.',hint:'Para testar com segurança, use primeiro a conta Demo.'},
  {icon:'2',title:'Deixe os ativos que quer acompanhar abertos',text:'O radar multiativo analisa os ativos cujas cotações estruturadas a página realmente estiver recebendo.',hint:'Se a CasaTrade só enviar dados do ativo em foco, o scanner vai avisar que precisa abrir aquele ativo para confirmar.'},
  {icon:'3',title:'Abra o Scanner e conecte a plataforma',text:'Clique em ABRIR SCANNER, depois em CONECTAR SCANNER com a CasaTrade aberta.',hint:'O scanner nunca precisa da sua senha, cookie ou token da corretora.'},
  {icon:'4',title:'Configure valor, vela e expiração',text:'Antes do START, informe o valor planejado e escolha a mesma vela e a mesma expiração que estão na CasaTrade.',hint:'Exemplo: vela M1 com expiração de 5 segundos é bloqueada. Se houver divergência, o scanner pausa.'},
  {icon:'5',title:'Espere o aquecimento e siga o estado',text:'Aguarde os 21 candles. SEARCHING procura, WATCH observa e CONFIRM indica oportunidade. BUY/SELL apenas prepara a entrada; o clique final é manual.',hint:'Não entre só porque apareceu uma direção. Espere o estado CONFIRM e confira o ativo e o tempo antes de operar.'}
];

function show(id){for(const x of ['activationView','tutorialView','customerView'])$(x).hidden=x!==id}
function fmtDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('pt-BR')}
function activeLicense(l){return !!l&&l.status==='active'&&(!l.expiresAt||Date.parse(l.expiresAt)>Date.now())}
function usage(l={}){if(l.plan==='trial'||l.isTrial){if(l.totalLimit!=null)return`${Number(l.usedTotal)||0} / ${l.totalLimit} total`;return`${Number(l.usedToday)||0} usado(s)`}if(l.dailyLimit==null)return`${Number(l.usedToday)||0} hoje • ilimitado`;return`${Number(l.usedToday)||0} / ${l.dailyLimit} hoje`}
function errorText(e){return({license_required:'Cole uma chave válida para ativar.',license_not_found:'Chave não encontrada. Confira e tente novamente.',license_inactive:'Esta licença está inativa. Renove ou fale com o suporte.',license_expired:'Esta licença venceu. Renove o acesso.',device_locked:'Esta licença já está vinculada a outro aparelho.',device_limit_reached:'Esta licença já atingiu o limite de aparelhos.',trial_limit_reached:'Seu Trial já utilizou todos os sinais disponíveis.',daily_limit_reached:'O limite diário deste plano foi atingido.',backend_unreachable:'Sem comunicação com o servidor agora. Seu acesso salvo continua disponível.',connect_code_invalid:'Código inválido, usado ou expirado.',trial_device_already_used:'Este aparelho já utilizou um Trial em outra conta.',permission_denied:'Permissão de acesso ao servidor ATS não foi concedida.'})[e]||'Não foi possível concluir. Tente novamente.'}
function terminalError(e){return ['license_not_found','license_inactive','license_expired','device_locked','device_limit_reached','trial_limit_reached'].includes(String(e||''))}
async function ensureInstallId(){const x=await chrome.storage.local.get('atsInstallationId');if(x.atsInstallationId)return x.atsInstallationId;const id=crypto.randomUUID();await chrome.storage.local.set({atsInstallationId:id});return id}
async function ensureApiPermission(){try{const origin=`${new URL(API).origin}/*`;const hp=manifest.host_permissions||[];if(hp.some(x=>x===origin||x.startsWith(new URL(API).origin)))return true;if(await chrome.permissions.contains({origins:[origin]}))return true;return await chrome.permissions.request({origins:[origin]})}catch{return false}}
async function storeSession(d,key=''){const set={[VALIDATED_AT]:Date.now()};if(key||d.licenseKey)set.atsLicenseKey=String(key||d.licenseKey||'');if(d.clientToken)set.atsClientToken=String(d.clientToken);if(d.clientTokenExpiresAt)set.atsClientTokenExpiresAt=Number(d.clientTokenExpiresAt)||0;if(d.accountToken)set.atsAccountToken=String(d.accountToken);if(d.accountTokenExpiresAt)set.atsAccountTokenExpiresAt=Number(d.accountTokenExpiresAt)||0;if(d.license)set[LICENSE_SNAPSHOT]=d.license;const old=(await chrome.storage.local.get('scannerState')).scannerState||{};if(d.license)set.scannerState={...old,license:{...(old.license||{}),...d.license,error:null}};await chrome.storage.local.set(set)}
async function directLicense(path,key){if(!(await ensureApiPermission()))return{ok:false,error:'permission_denied'};try{const r=await fetch(`${API}${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({licenseKey:String(key||'').trim().toUpperCase(),installationId:await ensureInstallId(),version:manifest.version})});const d=await r.json().catch(()=>({}));if(r.ok&&d.ok)await storeSession(d,key);return{ok:r.ok&&!!d.ok,status:r.status,...d}}catch{return{ok:false,error:'backend_unreachable'}}}
async function runtime(type,payload={}){try{return await chrome.runtime.sendMessage({type,...payload})}catch{return null}}
async function activateKey(key){const normalized=String(key||'').trim().toUpperCase();if(!normalized)return{ok:false,error:'license_required'};let r=await directLicense('/v1/license/activate',normalized);if(r?.ok){runtime('ATS_VALIDATE_LICENSE').catch(()=>{});return r}const rr=await runtime('ATS_ACTIVATE_LICENSE',{key:normalized});return rr||r||{ok:false,error:'backend_unreachable'}}
async function validateAccess(){const x=await chrome.storage.local.get('atsLicenseKey'),key=String(x.atsLicenseKey||'').trim();if(!key)return{ok:false,error:'license_required'};const direct=await Promise.race([directLicense('/v1/license/validate',key),new Promise(resolve=>setTimeout(()=>resolve({ok:false,error:'validation_timeout'}),2500))]);if(direct?.ok){runtime('ATS_VALIDATE_LICENSE').catch(()=>{});return direct}const rr=await Promise.race([runtime('ATS_VALIDATE_LICENSE'),new Promise(resolve=>setTimeout(()=>resolve(null),1200))]);return rr||direct}
async function getState(){const x=await chrome.storage.local.get(['scannerState',LICENSE_SNAPSHOT]);const local=x.scannerState||{};if(!local.license&&x[LICENSE_SNAPSHOT])local.license=x[LICENSE_SNAPSHOT];return local}

function renderCustomer(state={},message=''){currentState=state;const l=state.license||{};show('customerView');$('statusDot').classList.add('on');$('planName').textContent=(l.planLabel||l.plan||'ATIVO').toUpperCase();$('planBadge').textContent='ATIVO';$('planTitle').textContent=l.plan==='lifetime'?'Plano Vitalício ativo':'Acesso ativo';$('planText').textContent=l.plan==='lifetime'?'Seu acesso vitalício está vinculado a este aparelho.':'Sua licença está ativa e vinculada a este aparelho.';$('expiry').textContent=l.plan==='lifetime'?'VITALÍCIO':l.expiresAt?fmtDate(l.expiresAt):'SEM DATA';$('usage').textContent=usage(l);$('device').textContent=l.deviceLocked||Number(l.devices)>0?'VINCULADO':'LIVRE';$('customerStatus').className='notice ok';$('customerStatus').textContent=message||'Acesso pronto. A validação continua em segundo plano sem travar esta tela.'}
function renderActivation(state={},message=''){currentState=state;const l=state.license||{};show('activationView');$('statusDot').classList.remove('on');$('activationText').textContent=l.status==='expired'?'Seu acesso venceu. Você pode renovar ou ativar uma nova chave neste aparelho.':l.status==='device_locked'?'Esta licença está vinculada a outro aparelho. Use outra chave ou peça liberação ao suporte.':'Cole sua chave de licença para liberar o scanner neste aparelho.';if(message){$('activationStatus').className='notice bad';$('activationStatus').textContent=message}else{$('activationStatus').className='notice';$('activationStatus').textContent='Na primeira ativação, a licença fica vinculada a este aparelho.'}}
function renderTutorialStep(){const s=tutorialSteps[tutorialIndex];$('tutorialProgress').textContent=`${tutorialIndex+1} / ${tutorialSteps.length}`;$('tutorialIcon').textContent=s.icon;$('tutorialTitle').textContent=s.title;$('tutorialText').textContent=s.text;$('tutorialHint').textContent=s.hint;$('tutorialBack').disabled=tutorialIndex===0;$('tutorialNext').textContent=tutorialIndex===tutorialSteps.length-1?'ENTENDI • IR AO PAINEL':'PRÓXIMO'}
function showTutorial(state=currentState,index=0){currentState=state||currentState;tutorialIndex=Math.max(0,Math.min(index,tutorialSteps.length-1));show('tutorialView');$('statusDot').classList.add('on');renderTutorialStep()}
async function finishTutorial(){await chrome.storage.local.set({[ONBOARDING_KEY]:Date.now()});renderCustomer(currentState)}
async function maybeShowCustomerOrTutorial(state,forceTutorial=false){const x=await chrome.storage.local.get(ONBOARDING_KEY);if(forceTutorial||!x[ONBOARDING_KEY])showTutorial(state);else renderCustomer(state)}

async function refreshAccessSilently(){const r=await validateAccess().catch(()=>({ok:false,error:'backend_unreachable'}));if(r?.ok&&activeLicense(r.license)){const state=await getState();state.license=r.license;currentState=state;if(!$('tutorialView').hidden)return;if(!$('customerView').hidden)renderCustomer(state,'Acesso sincronizado agora.');return}if(terminalError(r?.error)){const state=await getState();renderActivation(state,errorText(r.error));return}if(!$('customerView').hidden){$('customerStatus').className='notice';$('customerStatus').textContent=errorText(r?.error||'backend_unreachable')}}
async function bootstrap(){const x=await chrome.storage.local.get(['scannerState','atsLicenseKey',LICENSE_SNAPSHOT,ONBOARDING_KEY]);const state=x.scannerState||{};if(!state.license&&x[LICENSE_SNAPSHOT])state.license=x[LICENSE_SNAPSHOT];const key=String(x.atsLicenseKey||'').trim();if(activeLicense(state.license)){currentState=state;if(!x[ONBOARDING_KEY])showTutorial(state);else renderCustomer(state);setTimeout(refreshAccessSilently,150);return}renderActivation(state,key?'Licença salva encontrada. Sincronizando em segundo plano...':'');if(key)setTimeout(refreshAccessSilently,100)}

async function activate(){const btn=$('activateBtn'),key=$('licenseKey').value;btn.disabled=true;btn.textContent='ATIVANDO...';$('activationStatus').className='notice';$('activationStatus').textContent='Validando licença e vinculando este aparelho...';const r=await activateKey(key);btn.disabled=false;btn.textContent='ATIVAR LICENÇA';if(r?.ok){$('licenseKey').value='';const state=await getState();state.license=r.license||state.license;currentState=state;showTutorial(state);return}$('activationStatus').className='notice bad';$('activationStatus').textContent=errorText(r?.error)}
async function connectAccount(){const btn=$('connectAccountBtn'),code=String($('accountCode').value||'').replace(/\D/g,'').slice(0,6);if(code.length!==6){$('activationStatus').className='notice bad';$('activationStatus').textContent='Digite os 6 números gerados no portal ATS.';return}btn.disabled=true;btn.textContent='CONECTANDO...';try{if(!(await ensureApiPermission()))throw Object.assign(new Error('permission_denied'),{code:'permission_denied'});const r=await fetch(`${API}/v1/customer/extension/exchange`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,installationId:await ensureInstallId(),version:manifest.version})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){$('activationStatus').className='notice bad';$('activationStatus').textContent=errorText(d.error||'connect_code_invalid');return}await storeSession(d);$('accountCode').value='';runtime('ATS_VALIDATE_LICENSE').catch(()=>{});const state=await getState();state.license=d.license||state.license;currentState=state;showTutorial(state)}catch(e){$('activationStatus').className='notice bad';$('activationStatus').textContent=errorText(e.code||'backend_unreachable')}finally{btn.disabled=false;btn.textContent='CONECTAR CONTA'}}
async function openScanner(){const btn=$('openScannerBtn');btn.disabled=true;btn.textContent='ABRINDO...';try{const url=chrome.runtime.getURL('src/sidepanel/index.html');await chrome.tabs.create({url,active:true});window.close()}catch{$('customerStatus').className='notice bad';$('customerStatus').textContent='Não consegui abrir o scanner neste navegador. Recarregue a extensão e tente novamente.';btn.disabled=false;btn.textContent='ABRIR SCANNER'}}
async function openPortal(){await chrome.tabs.create({url:`${API}/`,active:true});window.close()}
async function focusCasaTrade(){const tabs=await chrome.tabs.query({});const t=tabs.find(x=>/https:\/\/[^/]*casatrade\.(com|io)\//i.test(x.url||''));if(t?.id){await chrome.tabs.update(t.id,{active:true});if(t.windowId!=null)await chrome.windows.update(t.windowId,{focused:true}).catch(()=>{})}else await chrome.tabs.create({url:'https://trade.casatrade.com/',active:true})}
async function revalidate(){const b=$('validateBtn');b.disabled=true;$('customerStatus').className='notice';$('customerStatus').textContent='Sincronizando acesso...';const r=await validateAccess();b.disabled=false;if(r?.ok){const state=await getState();state.license=r.license||state.license;renderCustomer(state,'Acesso sincronizado agora.')}else if(terminalError(r?.error))renderActivation(currentState,errorText(r?.error));else{$('customerStatus').className='notice';$('customerStatus').textContent=errorText(r?.error)}}
function askRenewal(){const l=currentState.license||{};const msg=`Olá! Quero renovar meu acesso ao AI Trading Scanner. Plano atual: ${l.planLabel||l.plan||'não identificado'}.`;return`https://wa.me/${SUPPORT}?text=${encodeURIComponent(msg)}`}

$('activateBtn').addEventListener('click',activate);
$('licenseKey').addEventListener('keydown',e=>{if(e.key==='Enter')activate()});
$('accountCode').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,6)});
$('accountCode').addEventListener('keydown',e=>{if(e.key==='Enter')connectAccount()});
$('connectAccountBtn').addEventListener('click',connectAccount);
$('openPortalBtn').addEventListener('click',openPortal);
$('openScannerBtn').addEventListener('click',openScanner);
$('connectPlatformBtn').addEventListener('click',focusCasaTrade);
$('renewBtn').addEventListener('click',openPortal);
$('changeKeyBtn').addEventListener('click',()=>{renderActivation(currentState);$('licenseKey').focus()});
$('validateBtn').addEventListener('click',revalidate);
$('supportBtn').addEventListener('click',e=>{e.currentTarget.href=askRenewal()});
$('tutorialBtn').addEventListener('click',()=>showTutorial(currentState,0));
$('tutorialBack').addEventListener('click',()=>{if(tutorialIndex>0){tutorialIndex--;renderTutorialStep()}});
$('tutorialNext').addEventListener('click',async()=>{if(tutorialIndex<tutorialSteps.length-1){tutorialIndex++;renderTutorialStep();return}await finishTutorial()});
$('tutorialSkip').addEventListener('click',finishTutorial);

bootstrap();
