(()=>{
  if(globalThis.__ATS_ACCOUNT_LOGIN__)return;globalThis.__ATS_ACCOUNT_LOGIN__=true;
  const PUBLIC_API='https://ats-control-center-v07-production.up.railway.app';
  const INSTALL_KEY='atsInstallationId',ACCOUNT_TOKEN_KEY='atsAccountToken',ACCOUNT_EXP_KEY='atsAccountTokenExpiresAt',LICENSE_KEY='atsLicenseKey',CLIENT_TOKEN_KEY='atsClientToken',CLIENT_EXP_KEY='atsClientTokenExpiresAt';
  const $=s=>document.querySelector(s);
  async function settings(){return (await chrome.storage.local.get('settings')).settings||{}}
  function base(s={}){const raw=String(s.apiBase||'').trim();return(raw||PUBLIC_API).replace(/\/$/,'')}
  async function installId(){const x=await chrome.storage.local.get(INSTALL_KEY);if(x[INSTALL_KEY])return x[INSTALL_KEY];const id=crypto.randomUUID();await chrome.storage.local.set({[INSTALL_KEY]:id});return id}
  async function permission(url){try{const origin=new URL(url).origin+'/*';if(await chrome.permissions.contains({origins:[origin]}))return true;return chrome.permissions.request({origins:[origin]})}catch{return false}}
  async function saveSession(r){await chrome.storage.local.set({[LICENSE_KEY]:String(r.licenseKey||''),[CLIENT_TOKEN_KEY]:String(r.clientToken||''),[CLIENT_EXP_KEY]:Number(r.clientTokenExpiresAt)||0,[ACCOUNT_TOKEN_KEY]:String(r.accountToken||''),[ACCOUNT_EXP_KEY]:Number(r.accountTokenExpiresAt)||0});await chrome.runtime.sendMessage({type:'ATS_VALIDATE_LICENSE'}).catch(()=>{});return r}
  async function exchange(code){const s=await settings(),url=base(s);if(!(await permission(url)))return{ok:false,error:'permission_denied'};try{const r=await fetch(`${url}/v1/customer/extension/exchange`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:String(code||'').replace(/\D/g,''),installationId:await installId(),version:chrome.runtime.getManifest().version})});const d=await r.json().catch(()=>({}));if(!r.ok)return{ok:false,status:r.status,...d};return saveSession(d)}catch{return{ok:false,error:'backend_unreachable'}}}
  async function refresh(){const x=await chrome.storage.local.get([ACCOUNT_TOKEN_KEY,ACCOUNT_EXP_KEY]),token=String(x[ACCOUNT_TOKEN_KEY]||'');if(!token||Number(x[ACCOUNT_EXP_KEY]||0)<=Date.now())return false;const s=await settings(),url=base(s);try{const r=await fetch(`${url}/v1/customer/extension/refresh`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${token}`},body:JSON.stringify({installationId:await installId(),version:chrome.runtime.getManifest().version})});const d=await r.json().catch(()=>({}));if(!r.ok)return false;await saveSession({...d,accountToken:d.accountToken||token,accountTokenExpiresAt:d.accountTokenExpiresAt||x[ACCOUNT_EXP_KEY]});return true}catch{return false}}
  function inject(){const card=$('#licenseCard');if(!card||$('#accountAccessBox'))return;
    const style=document.createElement('style');style.textContent=`.account-access{margin:14px 0;padding:16px;border:1px solid #244761;border-radius:16px;background:linear-gradient(145deg,#0b1a2b,#08131f)}.account-access-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.account-access-head div{display:grid;gap:3px}.account-access-head b{font-size:14px}.account-access-head small{color:#88a4bc;line-height:1.35}.account-access-actions{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:12px}.account-access input{background:#07111d;border:1px solid #28475e;color:#fff;border-radius:11px;padding:13px;font-size:17px;font-weight:900;letter-spacing:.18em;text-align:center}.account-access button{border:0;border-radius:11px;padding:0 15px;background:linear-gradient(135deg,#4de2b7,#4a9dff);color:#031410;font-weight:950;cursor:pointer}.account-links{display:flex;justify-content:space-between;gap:8px;margin-top:10px}.account-links button{background:none;color:#77d8bd;padding:5px;font-size:11px}.account-status{display:block;color:#8fa8bf;font-size:11px;margin-top:9px;min-height:15px}.account-connected{border-color:#2b7963;background:#0c2924}`;document.head.appendChild(style);
    const box=document.createElement('section');box.id='accountAccessBox';box.className='account-access';box.innerHTML=`<div class="account-access-head"><div><b>ENTRAR NA MINHA CONTA</b><small>Gere um código no portal ATS e conecte esta instalação.</small></div><span>🔐</span></div><div class="account-access-actions"><input id="accountConnectCode" inputmode="numeric" maxlength="6" placeholder="000000"><button id="accountConnectBtn">CONECTAR</button></div><div class="account-links"><button id="openCustomerPortal">ABRIR PORTAL DO CLIENTE</button><button id="manualKeyToggle">USAR CHAVE MANUAL</button></div><small id="accountConnectStatus" class="account-status">A licença será vinculada automaticamente à sua conta.</small>`;
    const activation=$('#activationBox');activation?.before(box);if(activation)activation.hidden=true;
    $('#manualKeyToggle').onclick=()=>{if(activation)activation.hidden=!activation.hidden};
    $('#openCustomerPortal').onclick=async()=>{const s=await settings();chrome.tabs.create({url:`${base(s)}/`})};
    $('#accountConnectBtn').onclick=async()=>{const code=$('#accountConnectCode').value,status=$('#accountConnectStatus'),btn=$('#accountConnectBtn');if(code.replace(/\D/g,'').length!==6){status.textContent='Digite o código de 6 dígitos gerado no portal.';return}btn.disabled=true;btn.textContent='CONECTANDO...';status.textContent='Validando conta e vinculando este aparelho...';const r=await exchange(code);btn.disabled=false;btn.textContent='CONECTAR';if(r?.ok){box.classList.add('account-connected');status.textContent=`Conta conectada • ${r.license?.planLabel||r.license?.plan||'acesso ativo'}`;$('#licenseText').textContent='Conta vinculada e acesso sincronizado.';$('#accountConnectCode').value='';}else status.textContent=r?.error==='connect_code_invalid'?'Código inválido ou expirado.':r?.error==='trial_device_already_used'?'Este aparelho já utilizou um Trial em outra conta.':r?.error==='device_locked'?'Este acesso já está vinculado a outro aparelho.':'Não foi possível conectar. Verifique o portal e tente novamente.'};
  }
  inject();refresh().then(ok=>{if(ok&&$('#accountAccessBox')){$('#accountAccessBox').classList.add('account-connected');$('#accountConnectStatus').textContent='Conta conectada • sincronização automática ativa.'}});setInterval(refresh,60000);window.addEventListener('focus',refresh);
})();