(() => {
  const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
  let attention=[], busy=false;
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const daysLeft=l=>l?.expiresAt?Math.ceil((Date.parse(l.expiresAt)-Date.now())/86400000):null;
  const isActive=l=>l?.status==='active'&&(!l.expiresAt||Date.parse(l.expiresAt)>Date.now());

  const baseMessageFor=messageFor;
  messageFor=function(type,l={}){
    const name=String(l.customerName||'').trim()||'Cliente',key=l.key||q('#msgKey')?.value.trim()||'SUA-LICENÇA',plan=l.planLabel||l.plan||q('#msgPlan')?.value.trim()||'Plano',d=remainingDays(l),validity=d==null?'sem expiração':`${d} dia${d===1?'':'s'}`;
    if(type==='trial')return `🎁 *TESTE CONTROLADO LIBERADO!*\n\nOlá, ${name}! Seu teste do *AI Trading Scanner* foi criado com sucesso.\n\n✅ Plano: ${plan}\n⏳ Validade: ${validity}\n🎯 Limite do teste: ${l.totalLimit??2} sinais no total\n📱 Segurança: 1 aparelho por licença\n\n🔑 *Sua licença:*\n${key}\n\nDepois da primeira ativação, essa licença fica vinculada ao aparelho. A troca de dispositivo só pode ser liberada pelo administrador.\n\nAbra a extensão, cole a licença e conecte o scanner. 🚀`;
    if(type==='reset')return `♻️ *NOVO APARELHO LIBERADO!*\n\nOlá, ${name}! O vínculo anterior do seu *AI Trading Scanner* foi removido.\n\n🔑 Licença: ${key}\n\nAgora você pode ativar a extensão em um novo aparelho. O consumo já realizado foi mantido por segurança. ✅`;
    return baseMessageFor(type,l);
  };
  const baseSampleFor=sampleFor;
  sampleFor=function(type){if(type==='trial')return{customerName:q('#msgName')?.value||'Cliente',key:q('#msgKey')?.value||'ATS-XXXXXX-XXXXXX-XXXX',planLabel:q('#msgPlan')?.value||'Trial',dailyLimit:2,totalLimit:2,usedTotal:0,expiresAt:new Date(Date.now()+3*86400000).toISOString()};const s=baseSampleFor(type);if(s.planLabel==='Pro')s.dailyLimit=30;return s};

  const baseShowResult=showResult;
  showResult=function(title,l,type){baseShowResult(title,l,type);const box=q('#resultLicense');if(!box||!l)return;const rule=l.isTrial||l.plan==='trial'?`${l.totalLimit??2} sinais totais • 1 aparelho`:`${l.dailyLimit==null?'sem limite diário':`${l.dailyLimit} sinais/dia`} • 1 aparelho`;box.innerHTML=`<span>LICENÇA</span><strong>${safe(l.key)}</strong><small>${safe(l.planLabel||l.plan)} • ${safe(fmtDate(l.expiresAt))} • ${safe(rule)}</small>`};

  const baseRenderPlans=renderPlans;
  renderPlans=function(){baseRenderPlans();qa('#planStrip .plan-card').forEach((card,i)=>{const p=plans[i];if(!p)return;card.querySelector('span').textContent=p.id==='trial'?`${p.totalSignals??2} SINAIS NO TOTAL`:(p.dailySignals==null?'ILIMITADO':`${p.dailySignals} SINAIS/DIA`);card.querySelector('small').textContent='1 aparelho por licença'})};

  const baseOpenModal=openModal;
  openModal=function(mode,key=''){baseOpenModal(mode,key);if(mode==='trial'){q('#modalTitle').textContent='Gerar teste controlado';q('#modalDescription').textContent='Teste limitado a até 2 sinais no total e travado em um único aparelho.';q('#submitActionBtn').textContent='GERAR TESTE CONTROLADO'}if(mode==='reset'){q('#modalTitle').textContent='Liberar novo aparelho';q('#modalDescription').textContent='Remove apenas o vínculo do aparelho atual e mantém todo o consumo.';q('#submitActionBtn').textContent='LIBERAR NOVO APARELHO'}if(mode==='renew'){q('#renewFields')?.classList.remove('form-grid');q('#renewFields')?.classList.add('form-stack')}};
  qa('[data-renew-days]').forEach(btn=>btn.addEventListener('click',()=>{q('#renewDays').value=Number(btn.dataset.renewDays||30);qa('[data-renew-days]').forEach(x=>x.classList.toggle('active',x===btn))}));

  const baseInspector=renderInspector;
  renderInspector=function(){baseInspector();const l=licenses.find(x=>x.key===selectedLicenseKey),root=q('#licenseInspector');if(!l||!root)return;const grid=root.querySelector('.inspect-grid');if(grid&&!grid.querySelector('[data-total-usage]'))grid.insertAdjacentHTML('beforeend',`<div class="inspect-stat" data-total-usage><span>USO TOTAL</span><b>${l.totalLimit==null?(l.usedTotal??0):`${l.usedTotal??0} / ${l.totalLimit}`}</b></div><div class="inspect-stat"><span>VÍNCULO</span><b>${l.deviceLocked?'APARELHO VINCULADO':'LIVRE'}</b></div>`);const actions=root.querySelector('.inspect-actions');if(actions&&!root.querySelector('.quick-renew-inspector')){const bar=document.createElement('div');bar.className='quick-renew-inspector';bar.innerHTML='<span>Renovação rápida</span><button data-qrenew="7">+7</button><button data-qrenew="15">+15</button><button data-qrenew="30">+30</button><button data-qrenew="90">+90</button>';actions.insertAdjacentElement('afterend',bar);bar.querySelectorAll('[data-qrenew]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await api(`/v1/admin/licenses/${encodeURIComponent(l.key)}/renew`,{method:'POST',body:JSON.stringify({days:Number(b.dataset.qrenew)})});showResult('Acesso renovado',r.license,'renew');toast(`+${b.dataset.qrenew} dias adicionados`);await refreshData()}catch(e){toast(`Falha: ${e.message}`)}finally{b.disabled=false}})}};

  function buildAttention(){const items=[];for(const l of licenses){const d=daysLeft(l);if(l.status==='revoked')items.push({p:4,icon:'⛔',title:l.customerName||'Sem nome',text:'Licença bloqueada',key:l.key,a:'activate',label:'REATIVAR'});else if(d!=null&&d<=0)items.push({p:5,icon:'⌛',title:l.customerName||'Sem nome',text:'Licença expirada',key:l.key,a:'renew',label:'RENOVAR'});else if(d!=null&&d<=3)items.push({p:3,icon:'⚠️',title:l.customerName||'Sem nome',text:`Vence em ${d} dia${d===1?'':'s'}`,key:l.key,a:'renew',label:'RENOVAR'});if(l.plan==='trial'&&isActive(l)&&l.totalLimit!=null&&(l.remainingTotal??l.totalLimit)<=1)items.push({p:2,icon:'🎯',title:l.customerName||'Trial',text:`Trial com ${l.remainingTotal??0} sinal restante`,key:l.key,a:'view',label:'VER'})}const cutoff=Date.now()-86400000;for(const c of clients)if(!c.online&&c.lastSeen&&c.lastSeen<cutoff){const l=licenses.find(x=>x.key===c.licenseKey);if(l&&isActive(l))items.push({p:1,icon:'◌',title:c.customerName||'Cliente',text:`Offline há ${ago(c.lastSeen)}`,key:c.licenseKey,a:'view',label:'VER'})}attention=items.sort((a,b)=>b.p-a.p).slice(0,12)}
  function attentionAction(x){if(x.a==='renew')return openModal('renew',x.key);if(x.a==='activate')return api(`/v1/admin/licenses/${encodeURIComponent(x.key)}/activate`,{method:'POST'}).then(async()=>{toast('Licença reativada');await refreshData()}).catch(e=>toast(`Falha: ${e.message}`));selectedLicenseKey=x.key;setPage('licenses');renderLicenses();renderInspector()}
  function renderAttention(){buildAttention();const n=attention.length;q('#attentionCount')&&(q('#attentionCount').textContent=`${n} PENDÊNCIA${n===1?'':'S'}`);q('#notifyCount')&&(q('#notifyCount').textContent=n);q('#notifyPanelCount')&&(q('#notifyPanelCount').textContent=`${n} item${n===1?'':'s'}`);const html=n?attention.slice(0,6).map((x,i)=>`<div class="attention-row"><span class="attention-icon">${x.icon}</span><div><b>${safe(x.title)}</b><small>${safe(x.text)}</small></div><button class="attention-action" data-attention="${i}">${x.label}</button></div>`).join(''):'<div class="attention-empty">✓ Nada urgente agora. Operação em dia.</div>';q('#attentionList')&&(q('#attentionList').innerHTML=html);q('#notifyList')&&(q('#notifyList').innerHTML=n?attention.map((x,i)=>`<div class="notify-item"><div><b>${x.icon} ${safe(x.title)}</b><small>${safe(x.text)}</small></div><button data-notify-action="${i}">${x.label}</button></div>`).join(''):'<div class="attention-empty">Sem pendências.</div>');qa('[data-attention]').forEach(b=>b.onclick=()=>attentionAction(attention[Number(b.dataset.attention)]));qa('[data-notify-action]').forEach(b=>b.onclick=()=>{q('#notifyPanel').hidden=true;attentionAction(attention[Number(b.dataset.notifyAction)])});q('#heroSummary')&&(q('#heroSummary').textContent=n?`Você tem ${n} ação${n===1?'':'ões'} que merece${n===1?'':'m'} atenção hoje.`:'Tudo em ordem. Continue acompanhando licenças, clientes e consumo em tempo real.')}
  function renderCommercial(){const root=q('#commercialStats');if(!root)return;const paid=licenses.filter(l=>l.plan!=='trial'&&isActive(l)).length,trials=licenses.filter(l=>l.plan==='trial'&&isActive(l)).length,renewals=metrics.renewals??auditEvents.filter(e=>e.action==='license_renewed').length,locked=licenses.filter(l=>l.deviceLocked).length;root.innerHTML=[['ACESSOS PAGOS',paid,'licenças pagas ativas'],['TRIALS ATIVOS',trials,'até 2 sinais totais'],['RENOVAÇÕES',renewals,'registradas no histórico'],['APARELHOS VINCULADOS',locked,'1 vínculo por licença']].map(([a,b,c])=>`<div class="commercial-card"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('')}
  function renderGreeting(){const hr=new Date().getHours(),p=hr<12?'Bom dia':hr<18?'Boa tarde':'Boa noite';q('#greetingTitle')&&(q('#greetingTitle').textContent=`${p}. Sua operação está aqui.`);const t=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});q('#lastSync')&&(q('#lastSync').textContent=`última leitura ${t}`);q('#syncChip')&&(q('#syncChip').textContent=`✓ atualizado ${t}`)}
  function addMotion(){qa('.metric,.quick-card,.section-card,.client-card,.license-item,.plan-card').forEach((el,i)=>{if(el.dataset.opsMotion)return;el.dataset.opsMotion='1';el.classList.add('reveal');el.style.animationDelay=`${Math.min(i*20,160)}ms`})}
  function renderOps(){renderAttention();renderCommercial();renderGreeting();addMotion();renderInspector()}
  const baseRefresh=refreshData;refreshData=async function(){const r=await baseRefresh();renderOps();return r};
  q('#notifyBtn')?.addEventListener('click',e=>{e.stopPropagation();q('#notifyPanel').hidden=!q('#notifyPanel').hidden});document.addEventListener('click',e=>{if(!e.target.closest('.notify-wrap')&&q('#notifyPanel'))q('#notifyPanel').hidden=true});
  q('#globalSearch')?.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const term=e.currentTarget.value.trim();if(!term)return;setPage('licenses');q('#licenseSearch').value=term;renderLicenses();renderInspector()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();q('#globalSearch')?.focus()}});
  setInterval(async()=>{if(document.hidden||q('#authGate')?.hidden===false||busy)return;busy=true;try{await refreshData()}finally{busy=false}},15000);
  setTimeout(renderOps,500);

  const css=document.createElement('link');css.rel='stylesheet';css.href='crm.css?v=0.7.0';document.head.appendChild(css);
  const script=document.createElement('script');script.src='crm.js?v=0.7.0';script.defer=true;document.body.appendChild(script);
})();
