const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let config={plans:[]},me=null,authMode='signup',codeTimer=null,pendingVerificationEmail='';
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const date=v=>v?new Date(v).toLocaleDateString('pt-BR'):'—';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const cleanTextInput=v=>String(v??'').normalize('NFKC').replace(/[\u0000-\u001f\u007f-\u009f<>]/g,'').replace(/\s+/g,' ').trim();
const cleanEmailInput=v=>String(v??'').normalize('NFKC').replace(/[\u0000-\u001f\u007f-\u009f<>]/g,'').replace(/\s+/g,'').trim().toLowerCase();
function authPayload(form,includeName=false){const f=new FormData(form),raw=Object.fromEntries(f),out={email:cleanEmailInput(raw.email),password:String(raw.password||'')};if(includeName)out.name=cleanTextInput(raw.name);return out}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),3600)}
async function api(path,opt={}){const r=await fetch(path,{credentials:'same-origin',headers:{'content-type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||`HTTP ${r.status}`);e.status=r.status;e.data=d;throw e}return d}
function deliveryMessage(r={}){if(r.emailSent===true||r.emailDeliveryConfigured===true)return'Enviamos o link de confirmação. Confira a caixa de entrada e também o spam.';const reason=String(r.emailError||'');if(reason==='email_not_configured'||config.emailDeliveryConfigured===false)return'Sua conta foi criada, mas o servidor de e-mail ainda não está configurado. O administrador precisa configurar RESEND_API_KEY e EMAIL_FROM no Railway antes de o link poder ser enviado.';return'A conta foi criada, mas o provedor de e-mail não confirmou o envio. Tente reenviar em instantes ou fale com o suporte.'}
function planFeatures(p){if(p.id==='trial')return['Até 2 sinais no total','1 aparelho','Teste após e-mail confirmado'];if(p.lifetime||p.id==='lifetime')return['Sinais ilimitados','1 aparelho','Pagamento único','Acesso sem mensalidade'];const daily=p.dailySignals==null?'Sinais ilimitados':`${p.dailySignals} sinais por dia`;return[daily,'1 aparelho','Operação ao vivo','Suporte e atualizações']}
function renderPlans(target='#plansGrid',account=false){const el=$(target);if(!el)return;const rows=(config.plans||[]).filter(p=>p.id!=='trial');if(!rows.length){el.innerHTML='<div class="empty-state">Não foi possível carregar os planos agora. Atualize a página ou fale com o suporte.</div>';return}el.innerHTML=rows.map(p=>{const unavailable=account&&!config.paymentsConfigured,lifetime=p.lifetime||p.id==='lifetime',period=lifetime?'pagamento único':'/ 30 dias',button=lifetime?'COMPRAR VITALÍCIO':account?'ASSINAR / MIGRAR':'COMEÇAR AGORA';return`<article class="plan-card ${p.recommended?'recommended':''}">${p.recommended?'<span class="recommended-tag">RECOMENDADO</span>':lifetime?'<span class="recommended-tag">PAGAMENTO ÚNICO</span>':''}<span class="eyebrow">${p.label||p.id}</span><h3>${p.label||p.id}</h3><div class="price">${money(p.price)} <small>${period}</small></div><div class="plan-features">${planFeatures(p).map(x=>`<span>✓ ${x}</span>`).join('')}</div><button class="${p.recommended?'primary':'secondary'}" data-plan="${p.id}" ${unavailable?'disabled':''}>${unavailable?'PAGAMENTO EM CONFIGURAÇÃO':button}</button></article>`}).join('');el.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>account?checkout(b.dataset.plan):openAuth('signup'))}
function openAuth(mode='signup'){authMode=mode;$('#authModal').hidden=false;$('#signupForm').hidden=mode!=='signup';$('#loginForm').hidden=mode!=='login';$('#authTitle').textContent=mode==='signup'?'Criar sua conta':'Entrar na sua conta';$('#authSub').textContent=mode==='signup'?'Confirme seu e-mail para liberar o Trial.':'Acesse seu plano, dispositivo e pagamentos.';$('#authSwitch').textContent=mode==='signup'?'Já tenho conta • Entrar':'Ainda não tenho conta • Criar';$('#authMsg').textContent='';document.body.style.overflow='hidden';setTimeout(()=>$('#authModal input:not([hidden])')?.focus(),50)}
function closeAuth(){$('#authModal').hidden=true;document.body.style.overflow=''}
function openVerification(email='',message=''){pendingVerificationEmail=cleanEmailInput(email||pendingVerificationEmail);closeAuth();$('#verifyView').hidden=false;$('#verifyText').textContent=message||'Enviamos um link para seu e-mail. Depois da confirmação, seu Trial é liberado automaticamente.';$('#resendVerification').hidden=!pendingVerificationEmail}
function closeVerification(){$('#verifyView').hidden=true}
function accessActive(l){return !!l&&l.status==='active'&&(!l.expiresAt||Date.parse(l.expiresAt)>Date.now())}
function showAccount(){if(!me)return;$('#publicView').hidden=true;$('#accountView').hidden=false;$('.site-header').hidden=true;$('.site-footer').hidden=true;$('#accountBtn').textContent='MINHA CONTA';const a=me.account,l=a.license,trial=l?.plan==='trial',lifetime=!!l?.lifetime||l?.plan==='lifetime',active=accessActive(l);$('#helloTitle').textContent=`Olá, ${String(a.name||'Trader').split(' ')[0]} 👋`;$('#accountEmail').textContent=a.email;$('#planTitle').textContent=l?`${l.planLabel||l.plan}${active?' ativo':' • atenção'}`:'Acesso em preparação';$('#planText').textContent=trial?'Seu teste é controlado e termina após o limite total de sinais.':lifetime&&active?'Seu acesso vitalício está ativo nesta conta.':active?'Seu acesso está sincronizado com a conta.':'Seu acesso precisa ser renovado ou reativado.';$('#kpiPlan').textContent=l?.planLabel||'—';$('#kpiExpiry').textContent=lifetime?'sem vencimento':l?.expiresAt?`até ${date(l.expiresAt)}`:'—';if(trial){$('#kpiUsageLabel').textContent='USO DO TRIAL';$('#kpiUsage').textContent=l?.totalLimit==null?String(l?.usedTotal??0):`${l?.usedTotal??0} / ${l.totalLimit}`}else{$('#kpiUsageLabel').textContent='USO HOJE';$('#kpiUsage').textContent=l?`${l.usedToday??0}${l.dailyLimit==null?'':` / ${l.dailyLimit}`}`:'—'}$('#kpiDevice').textContent=l?.deviceLocked?'VINCULADO':'LIVRE';$('#kpiStatus').textContent=active?'ATIVO':String(l?.status||'—').toUpperCase();$('#accountStatus').textContent=active?'ATIVO':'VERIFICAR';const next=$('#nextAction');if(!active||(trial&&Number(l.remainingTotal)===0)){if(trial&&Number(l.remainingTotal)===0){$('#nextTitle').textContent='Seu Trial terminou';$('#nextText').textContent='Escolha um plano para continuar usando o scanner.'}else{$('#nextTitle').textContent='Regularize seu acesso';$('#nextText').textContent='Escolha um plano ou renove para continuar usando a extensão.'}next.dataset.accountPage='plans';next.textContent='VER PLANOS'}else{$('#nextTitle').textContent=l?.deviceLocked?'Acesso pronto':'Conecte sua extensão';$('#nextText').textContent=l?.deviceLocked?'Este plano já está vinculado ao seu aparelho. Abra a extensão para continuar.':'Baixe a extensão, gere o código de 6 dígitos e conecte esta conta ao navegador.';next.dataset.accountPage='device';next.textContent=l?.deviceLocked?'GERENCIAR CONEXÃO':'BAIXAR / GERAR CÓDIGO'}renderPlans('#accountPlans',true)}
function showPublic(){$('#publicView').hidden=false;$('#accountView').hidden=true;$('.site-header').hidden=false;$('.site-footer').hidden=false;$('#accountBtn').textContent='ENTRAR'}
async function refreshMe(){try{me=await api('/v1/customer/me');showAccount();return true}catch{me=null;showPublic();return false}}
function page(name){$$('[data-account-page]').forEach(b=>b.classList.toggle('active',b.dataset.accountPage===name));$$('[data-account-view]').forEach(v=>v.classList.toggle('active',v.dataset.accountView===name));if(name==='plans')renderPlans('#accountPlans',true)}
async function signup(e){e.preventDefault();const payload=authPayload(e.currentTarget,true);pendingVerificationEmail=payload.email;$('#authMsg').textContent='Criando conta...';try{const r=await api('/v1/customer/signup',{method:'POST',body:JSON.stringify(payload)});openVerification(pendingVerificationEmail,deliveryMessage(r))}catch(err){$('#authMsg').textContent=err.message==='email_in_use'?'Este e-mail já possui conta.':err.message==='invalid_signup'?'Confira nome, e-mail e senha (mínimo 8 caracteres).':err.message==='too_many_attempts'?'Muitas tentativas. Aguarde um pouco e tente novamente.':'Não foi possível criar a conta.'}}
async function login(e){e.preventDefault();const payload=authPayload(e.currentTarget,false);$('#authMsg').textContent='Entrando...';try{await api('/v1/customer/login',{method:'POST',body:JSON.stringify(payload)});closeAuth();await refreshMe()}catch(err){if(err.message==='email_not_verified'){openVerification(payload.email,config.emailDeliveryConfigured?'Seu e-mail ainda não foi confirmado. Abra o link recebido ou peça um novo envio abaixo.':'Seu e-mail ainda não foi confirmado, e o serviço de envio está sem configuração no servidor. O administrador precisa configurar Resend antes do reenvio.');return}$('#authMsg').textContent=err.message==='invalid_credentials'?'E-mail ou senha incorretos.':err.message==='too_many_attempts'?'Muitas tentativas. Aguarde um pouco.':'Falha ao entrar.'}}
async function resendVerification(){if(!pendingVerificationEmail)return toast('Informe seu e-mail no cadastro ou login.');const b=$('#resendVerification');b.disabled=true;b.textContent='REENVIANDO...';try{const r=await api('/v1/customer/resend-verification',{method:'POST',body:JSON.stringify({email:pendingVerificationEmail})});toast(deliveryMessage(r))}catch(err){toast(err.message==='too_many_attempts'?'Muitas tentativas de reenvio. Aguarde um pouco.':'Não foi possível reenviar agora.')}finally{b.disabled=false;b.textContent='REENVIAR E-MAIL'}}
async function googleLogin(resp){try{await api('/v1/customer/google',{method:'POST',body:JSON.stringify({credential:String(resp?.credential||'')})});closeAuth();await refreshMe()}catch{toast('Não foi possível entrar com Google.')}}
function setupGoogle(){if(!config.googleClientId)return;$('#googleWrap').hidden=false;const go=()=>{if(!globalThis.google?.accounts?.id)return setTimeout(go,300);google.accounts.id.initialize({client_id:config.googleClientId,callback:googleLogin});google.accounts.id.renderButton($('#googleButton'),{theme:'filled_black',size:'large',width:400,text:'continue_with'})};go()}
async function verifyFromUrl(){const u=new URL(location.href),token=u.searchParams.get('verify');if(!token)return;$('#verifyView').hidden=false;$('#verifyText').textContent='Confirmando seu e-mail e liberando o Trial...';$('#resendVerification').hidden=true;try{await api('/v1/customer/verify-email',{method:'POST',body:JSON.stringify({token:String(token)})});u.searchParams.delete('verify');history.replaceState({},'',u.pathname+u.search);closeVerification();pendingVerificationEmail='';await refreshMe();toast('E-mail confirmado. Sua conta e o Trial foram liberados.')}catch{$('#verifyText').textContent='Este link de confirmação é inválido ou expirou. Entre novamente para solicitar um novo envio.'}}
async function generateCode(){const b=$('#generateCode');b.disabled=true;b.textContent='GERANDO...';try{const r=await api('/v1/customer/connect-code',{method:'POST',body:'{}'});$('#connectCode').textContent=r.code;$('#connectCodeBox').hidden=false;let left=Math.max(0,Math.floor((r.expiresAt-Date.now())/1000));clearInterval(codeTimer);const tick=()=>{$('#connectExpiry').textContent=`expira em ${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left--<=0){clearInterval(codeTimer);$('#connectExpiry').textContent='código expirado'}};tick();codeTimer=setInterval(tick,1000)}catch(err){toast(err.message==='access_inactive'?'Seu acesso precisa ser renovado antes de conectar a extensão.':'Não foi possível gerar o código.')}finally{b.disabled=false;b.textContent='GERAR NOVO CÓDIGO'}}
async function copyConnectCode(){const code=$('#connectCode').textContent.trim();if(!/^\d{6}$/.test(code))return toast('Gere um código primeiro.');try{await navigator.clipboard.writeText(code);toast('Código copiado. Abra a extensão e cole os 6 dígitos.')}catch{toast('Não foi possível copiar automaticamente.')}}
async function checkout(plan){if(!config.paymentsConfigured)return toast('Pagamento online ainda está sendo configurado. Fale com o suporte.');try{const r=await api('/v1/customer/checkout',{method:'POST',body:JSON.stringify({plan:String(plan||'')})});location.href=r.checkoutUrl}catch(err){toast(err.message==='payment_not_configured'?'Pagamento ainda está sendo configurado.':'Não foi possível iniciar o pagamento.')}}
function setupAvailability(){const issues=[];if(!config.emailDeliveryConfigured)issues.push('e-mail de confirmação (Resend não configurado)');if(!config.paymentsConfigured)issues.push('pagamento online');if(issues.length){$('#serviceNotice').hidden=false;$('#serviceNoticeText').textContent=`Em configuração: ${issues.join(' e ')}. O site mostra o status real e não finge que um e-mail ou pagamento foi concluído.`}$('#paymentNotice').hidden=!!config.paymentsConfigured}
function cleanPaymentParam(){const u=new URL(location.href);if(!u.searchParams.has('payment'))return;u.searchParams.delete('payment');history.replaceState({},'',u.pathname+(u.search?u.search:''))}
async function handlePaymentReturn(){const p=new URL(location.href).searchParams.get('payment');if(!p)return;if(p==='failure'){toast('Pagamento não concluído. Você pode tentar novamente.');cleanPaymentParam();return}if(p==='pending'){toast('Pagamento pendente. O acesso será atualizado após aprovação confirmada pelo servidor.');cleanPaymentParam();return}if(p!=='success')return;toast('Retorno do checkout recebido. Confirmando pagamento com o servidor...');for(let i=0;i<8;i++){await refreshMe();const l=me?.account?.license;if(l&&l.plan!=='trial'&&accessActive(l)){toast(`Plano ${l.planLabel||l.plan} liberado com sucesso.`);cleanPaymentParam();return}await sleep(1500)}toast('Ainda não há confirmação do pagamento no servidor. Aguarde a aprovação do provedor e atualize em instantes.');cleanPaymentParam()}
async function init(){config=await api('/v1/public/config').catch(()=>({plans:[],emailDeliveryConfigured:false,paymentsConfigured:false}));renderPlans();setupGoogle();setupAvailability();if(config.supportWhatsapp){const wa=`https://wa.me/${config.supportWhatsapp}`;['#supportTop','#supportRail','#supportFooter'].forEach(sel=>{const el=$(sel);if(el)el.href=wa})}if(config.casaTradeUrl){$('#casaTradeBtn').href=config.casaTradeUrl;$('#casaTradeBtn').hidden=false}await verifyFromUrl();await refreshMe();await handlePaymentReturn()}
$('#accountBtn').onclick=()=>me?showAccount():openAuth('login');$$('[data-open-auth]').forEach(b=>b.onclick=()=>openAuth(b.dataset.openAuth));$$('[data-close-auth]').forEach(b=>b.onclick=closeAuth);$('#authSwitch').onclick=()=>openAuth(authMode==='signup'?'login':'signup');$('#signupForm').addEventListener('submit',signup);$('#loginForm').addEventListener('submit',login);$('#backLogin').onclick=()=>{closeVerification();openAuth('login')};$('#resendVerification').onclick=resendVerification;$('#logoutBtn').onclick=async()=>{await api('/v1/customer/logout',{method:'POST',body:'{}'}).catch(()=>{});clearInterval(codeTimer);me=null;showPublic()};$$('[data-account-page]').forEach(b=>b.onclick=()=>page(b.dataset.accountPage));$('#generateCode').onclick=generateCode;$('#copyConnectCode').onclick=copyConnectCode;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#authModal').hidden)closeAuth()});init();