const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let config={plans:[]},me=null,authMode='signup',codeTimer=null;
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const date=v=>v?new Date(v).toLocaleDateString('pt-BR'):'—';
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
async function api(path,opt={}){const r=await fetch(path,{credentials:'same-origin',headers:{'content-type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||`HTTP ${r.status}`);e.status=r.status;e.data=d;throw e}return d}
function planFeatures(p){if(p.id==='trial')return['Até 2 sinais no total','1 aparelho','Teste após e-mail confirmado'];const daily=p.dailySignals==null?'Sinais ilimitados':`${p.dailySignals} sinais por dia`;return[daily,'1 aparelho','Operação ao vivo','Suporte e atualizações']}
function renderPlans(target='#plansGrid',account=false){const el=$(target);if(!el)return;const rows=(config.plans||[]).filter(p=>p.id!=='trial');el.innerHTML=rows.map(p=>`<article class="plan-card ${p.recommended?'recommended':''}">${p.recommended?'<span class="recommended-tag">RECOMENDADO</span>':''}<span class="eyebrow">${p.label||p.id}</span><h3>${p.label||p.id}</h3><div class="price">${money(p.price)} <small>/ 30 dias</small></div><div class="plan-features">${planFeatures(p).map(x=>`<span>✓ ${x}</span>`).join('')}</div><button class="${p.recommended?'primary':'secondary'}" data-plan="${p.id}">${account?'ASSINAR / MIGRAR':'COMEÇAR AGORA'}</button></article>`).join('');el.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>account?checkout(b.dataset.plan):openAuth('signup'))}
function openAuth(mode='signup'){authMode=mode;$('#authModal').hidden=false;$('#signupForm').hidden=mode!=='signup';$('#loginForm').hidden=mode!=='login';$('#authTitle').textContent=mode==='signup'?'Criar sua conta':'Entrar na sua conta';$('#authSub').textContent=mode==='signup'?'Confirme seu e-mail para liberar o Trial.':'Acesse seu plano, dispositivo e pagamentos.';$('#authSwitch').textContent=mode==='signup'?'Já tenho conta • Entrar':'Ainda não tenho conta • Criar';$('#authMsg').textContent=''}
function closeAuth(){$('#authModal').hidden=true}
function showAccount(){if(!me)return;$('#publicView').hidden=true;$('#accountView').hidden=false;$('#accountBtn').textContent='MINHA CONTA';const a=me.account,l=a.license;$('#helloTitle').textContent=`Olá, ${String(a.name||'Trader').split(' ')[0]} 👋`;$('#accountEmail').textContent=a.email;$('#planTitle').textContent=l?`${l.planLabel||l.plan} ativo`:'Acesso em preparação';$('#planText').textContent=l?.plan==='trial'?'Seu teste é controlado e termina após o limite total de sinais.':'Seu acesso está sincronizado com a conta.';$('#kpiPlan').textContent=l?.planLabel||'—';$('#kpiExpiry').textContent=l?.expiresAt?`até ${date(l.expiresAt)}`:'—';$('#kpiUsage').textContent=l?`${l.usedToday}${l.dailyLimit==null?'':` / ${l.dailyLimit}`}`:'—';$('#kpiDevice').textContent=l?.deviceLocked?'VINCULADO':'LIVRE';$('#kpiStatus').textContent=l?.status==='active'?'ATIVO':String(l?.status||'—').toUpperCase();$('#accountStatus').textContent=l?.status==='active'?'ATIVO':'VERIFICAR';if(l?.plan==='trial'&&Number(l.remainingTotal)===0){$('#nextTitle').textContent='Seu Trial terminou';$('#nextText').textContent='Escolha um plano para continuar usando o scanner.'}renderPlans('#accountPlans',true)}
function showPublic(){$('#publicView').hidden=false;$('#accountView').hidden=true;$('#accountBtn').textContent='ENTRAR'}
async function refreshMe(){try{me=await api('/v1/customer/me');showAccount()}catch{me=null;showPublic()}}
function page(name){$$('[data-account-page]').forEach(b=>b.classList.toggle('active',b.dataset.accountPage===name));$$('[data-account-view]').forEach(v=>v.classList.toggle('active',v.dataset.accountView===name));if(name==='plans')renderPlans('#accountPlans',true)}
async function signup(e){e.preventDefault();const f=new FormData(e.currentTarget),payload=Object.fromEntries(f);$('#authMsg').textContent='Criando conta...';try{const r=await api('/v1/customer/signup',{method:'POST',body:JSON.stringify(payload)});closeAuth();$('#verifyView').hidden=false;$('#verifyText').textContent=r.emailDeliveryConfigured?'Enviamos um link de confirmação para seu e-mail. Depois de confirmar, o Trial será criado automaticamente.':'Sua conta foi criada, mas o envio de e-mail ainda está sendo configurado. Fale com o suporte para concluir a ativação.'}catch(err){$('#authMsg').textContent=err.message==='email_in_use'?'Este e-mail já possui conta.':err.message==='invalid_signup'?'Confira nome, e-mail e senha (mínimo 8 caracteres).':'Não foi possível criar a conta.'}}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),payload=Object.fromEntries(f);$('#authMsg').textContent='Entrando...';try{await api('/v1/customer/login',{method:'POST',body:JSON.stringify(payload)});closeAuth();await refreshMe()}catch(err){$('#authMsg').textContent=err.message==='email_not_verified'?'Confirme seu e-mail antes de entrar.':err.message==='invalid_credentials'?'E-mail ou senha incorretos.':'Falha ao entrar.'}}
async function googleLogin(resp){try{await api('/v1/customer/google',{method:'POST',body:JSON.stringify({credential:resp.credential})});closeAuth();await refreshMe()}catch{toast('Não foi possível entrar com Google.')}}
function setupGoogle(){if(!config.googleClientId)return;$('#googleWrap').hidden=false;const go=()=>{if(!globalThis.google?.accounts?.id)return setTimeout(go,300);google.accounts.id.initialize({client_id:config.googleClientId,callback:googleLogin});google.accounts.id.renderButton($('#googleButton'),{theme:'filled_black',size:'large',width:400,text:'continue_with'})};go()}
async function verifyFromUrl(){const u=new URL(location.href),token=u.searchParams.get('verify');if(!token)return;$('#verifyView').hidden=false;$('#verifyText').textContent='Confirmando seu e-mail e liberando o Trial...';try{await api('/v1/customer/verify-email',{method:'POST',body:JSON.stringify({token})});u.searchParams.delete('verify');history.replaceState({},'',u.pathname+u.search);$('#verifyView').hidden=true;await refreshMe();toast('E-mail confirmado. Trial liberado!')}catch{$('#verifyText').textContent='Este link de confirmação é inválido ou expirou.'}}
async function generateCode(){const b=$('#generateCode');b.disabled=true;b.textContent='GERANDO...';try{const r=await api('/v1/customer/connect-code',{method:'POST',body:'{}'});$('#connectCode').textContent=r.code;$('#connectCodeBox').hidden=false;let left=Math.max(0,Math.floor((r.expiresAt-Date.now())/1000));clearInterval(codeTimer);const tick=()=>{$('#connectExpiry').textContent=`expira em ${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left--<=0){clearInterval(codeTimer);$('#connectExpiry').textContent='código expirado'}};tick();codeTimer=setInterval(tick,1000)}catch{toast('Não foi possível gerar o código.')}finally{b.disabled=false;b.textContent='GERAR NOVO CÓDIGO'}}
async function checkout(plan){try{const r=await api('/v1/customer/checkout',{method:'POST',body:JSON.stringify({plan})});location.href=r.checkoutUrl}catch(err){toast(err.message==='payment_not_configured'?'Pagamento ainda está sendo configurado.':'Não foi possível iniciar o pagamento.')}}
async function init(){config=await api('/v1/public/config').catch(()=>({plans:[]}));renderPlans();setupGoogle();if(config.supportWhatsapp){const wa=`https://wa.me/${config.supportWhatsapp}`;$('#supportTop').href=wa;$('#supportRail').href=wa}if(config.casaTradeUrl){$('#casaTradeBtn').href=config.casaTradeUrl;$('#casaTradeBtn').hidden=false}await verifyFromUrl();await refreshMe();const p=new URL(location.href).searchParams.get('payment');if(p==='success')toast('Pagamento recebido. Atualizando seu acesso...');if(p==='pending')toast('Pagamento pendente. O acesso será atualizado após aprovação.')}
$('#accountBtn').onclick=()=>me?showAccount():openAuth('login');$$('[data-open-auth]').forEach(b=>b.onclick=()=>openAuth(b.dataset.openAuth));$$('[data-close-auth]').forEach(b=>b.onclick=closeAuth);$('#authSwitch').onclick=()=>openAuth(authMode==='signup'?'login':'signup');$('#signupForm').addEventListener('submit',signup);$('#loginForm').addEventListener('submit',login);$('#backLogin').onclick=()=>{$('#verifyView').hidden=true;openAuth('login')};$('#logoutBtn').onclick=async()=>{await api('/v1/customer/logout',{method:'POST',body:'{}'}).catch(()=>{});me=null;showPublic()};$$('[data-account-page]').forEach(b=>b.onclick=()=>page(b.dataset.accountPage));$('#generateCode').onclick=generateCode;init();